# Puerto
server.port=8080

# H2 - base de datos en memoria
spring.datasource.url=jdbc:h2:mem:parkingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 (para ver tus tablas en el navegador mientras desarrollas)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA - crea las tablas automaticamente desde tus entidades
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true